version: '3.1'

services:
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
      POSTGRES_DB: pectometro
    ports:
      - '5432:5432'
